theme: jekyll-theme-cayman
title: Towards Semantic Interpretation of Thoracic Disease and COVID-19 Diagnosis Models
description: Medical Image Computing and Computer Assisted Intervention (MICCAI) 2021
